site_name: MkDocs Poetry Tutorial
docs_dir: docs

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    #- navigation.tabs
    #- navigation.sections
    
    - toc.follow #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - tags

plugins:
  - search
  - macros
  # - tags:
  #     tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/YOUR_GITHUB_USERNAME
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/YOUR_TWITTER_USERNAME
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/YOUR_LINKEDIN_USERNAME

copyright: Copyright &copy; 2023 Your Name

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - meta

# Define only part of the navigation manually
nav:
  - Index: index.md
  - AWS: aws.md
  - Python Reference:
    - Index: dev/python-language-reference-nicola.md
    - Variables, Constants, and Naming: dev/python-language-reference-nicola/variables-constants-and-naming.md
    - Data Types and Literals: dev/python-language-reference-nicola/data-types-and-literals.md
    - Functions and Functional Programming: dev/python-language-reference-nicola/functions-and-functional-programming.md
    - Expressions and Operators: dev/python-language-reference-nicola/expressions-and-operators.md
    - Control Flow: dev/python-language-reference-nicola/control-flow.md
    - Classes and Objects: dev/python-language-reference-nicola/classes-and-objects.md
    - Built-in Exceptions: dev/python-language-reference-nicola/builtin-exceptions.md
    - Modules: dev/python-language-reference-nicola/modules.md
    - Packages: dev/python-language-reference-nicola/packages.md

#- ... | docker-*.md


  # - Guides:  # You can define a folder manually
  #     - Getting Started: guides/getting-started.md
