== Salamba Shirshasana

* https://www.yogapedia.com/definition/6982/salamba-sirsasana


Salamba sirsasana is a variation of sirsasana (the traditional headstand).

Salamba is a Sanskrit word meaning “to support.” Its opposite is niralamba, which means “unsupported” or “without support.”

Salamba describes a pose in which the yogi uses the hands, arms or other type of support for balance or to otherwise aid in exercise of the posture.







NOTE: Salamba yoga poses should be mastered before the yogi attempts the more challenging niralamba versions. Some common salamba poses include:

* Salamba kapotasana (supported pigeon) - a half split with the hands placed on the ground for support
* Salamba sarvangasana (supported shoulder stand) - the upper arms rest on the ground and the hands rest on the lower back
* Salamba bhujangasana (supported cobra, or sphinx) - the forearms provide support for the backbend
* Salamba sirsasana (supported headstand) - the forearms and interlocked hands form a sort of basket to support the head and provide balance
* Salamba balasana (supported child's pose) - the torso and head rest on a prop, typically a rolled-up blanket or several blankets
