== Urdhva Dhanurasana

(OORD-vah don-your-AHS-anna)

Upward Bow (Wheel) Pose

urdhva = upward
dhanu = bow

Ref:

* https://www.yogajournal.com/poses/upward-bow-or-wheel-pose
* Your Glutes in Backbends: Part I
 http://www.dailybandha.com/2017/05/your-glutes-in-backbends-part-i.html?m=1

Videos:

* Questo non mi sembra male ma da capire ... https://www.youtube.com/watch?v=VuHFauy13o8




Benefits:

* strengthen your arms, legs, abdomen, and spine
* Stretches the chest and lungs
* Strengthens the arms and wrists, legs, buttocks, abdomen, and spine
* Stimulates the thyroid and pituitary
* Increases energy and counteracts depression
* Therapeutic for asthma, back pain, infertility, and osteoporosis
* energy boost

Contraindications and Cautions

* Back injury
* Carpal tunnel syndrome
* Diarrhea
* Headache
* Heart problems
* High or low blood pressure



Preparatory Poses:

* Bhujangasana
* Setu Bandha Sarvangasana
* Urdhva Mukha Svanasana
* Virasana

Follow-up Poses

* Ardha Matsyendrasana
* Supta Padangusthasana

== Partnering
A partner can help you learn about the work in the shoulders in this pose. Have your partner stand at your head, facing you. Perform the pose. Your partner can bring his/her hands around the sides of your torso so that his/her palms cover the shoulder blades and encourage them to widen away from the spine.

== Variations
Eka Pada Urdhva Dhanurasana (pronounced ACHE-ah POD-ah, eka = one, pada = foot or leg)

Perform Urdhva Dhanurasana. Shift your weight onto the left foot and, with an exhalation, bend your right knee and draw it into your torso. Then inhale and extend the right leg at about a 45 degree angle relative to the floor. Hold for 5 to 10 seconds, exhale, bend the knee and return the foot to the floor. Repeat with the left leg for the same length of time.

== Beginner's Tip
The knees and feet tend to splay as you lift into this pose, which compresses the lower back. In the beginning position, loop and secure a strap around your thighs, just above the knees, to hold the thighs at hip width and parallel to each other. To keep the feet from turning out, place a block between them, with the bases of the big toes pressing the ends of the block. As you go up, press the feet into the block.
