== Adho Mukha Svanasana - Downward Facing Dog

* http://www.dailybandha.com/2011/03/balancing-forearms-wrists-and-hands-in.html
* https://www.yogajournal.com/poses/4-steps-master-adho-mukha-svanasana
* Video semplice con focus sulle spalle e il braccio: https://www.youtube.com/watch?v=jt6-ju49FkQ&feature=youtu.be
* https://www.yogajournal.com/poses/downward-facing-dog

(AH-doh MOO-kah shvah-NAHS-anna)

* adho = downward
* mukha = face
* svana = dog

Benefits:

* stability in your hands and feet
* a more extended spine



https://yogainternational.com/article/view/how-to-find-your-perfect-downward-facing-dog


When you find the optimal downdog alignment for your body and then commit that alignment to your muscle memory, you may not only discover a newfound strength and flexibility, but also the ability to truly relax into this “resting” asana.


Is one of the most frequented posture, but also one of the most commonly misaligned postures in yoga.

As the whole body is utilized during this asana, and joints that do not typically bear the weight of the body (the elbows and wrists) are now holding its mass, it is of crucial importance that the posture is safely aligned.


When done right it's a "resting posture", which may sound absurd to those who struggle to hold the position. But when practiced regularly, with healthy alignment, downdog may really start to feel almost effortless as you use the structure of your skeletal system to support the weight of your body.


