== Savasana or Mrtasana - Corpse pose

https://www.yogajournal.com/poses/corpse-pose

Is a pose of total relaxation—making it one of the most challenging.

Is also called Mrtasana (pronounced mrit-TAHS-anna, mrta = death)

See a video demonstration of how to set up for Corpse Pose: https://www.yogajournal.com/videos/savasana

=== Step 1
In Savasana it's essential that the body be placed in a neutral position.

Sit on the floor with your knees bent, feet on the floor, and lean back onto your forearms. Lift your pelvis slightly off the floor and, with your hands, push the back of the pelvis toward the tailbone (coccige), then return the pelvis to the floor. Inhale and slowly extend the right leg, then the left, pushing through the heels. Release both legs, softening the groins, and see that the legs are angled evenly relative to the mid-line of the torso, and that the feet turn out equally. Narrow the front pelvis and soften (but don't flatten) the lower back.

=== Step 2

With your hands lift the base of the skull away from the back of the neck and release the back of the neck down toward the tailbone. If you have any difficulty doing this, support the back of the head and neck on a folded blanket. Broaden the base of the skull too, and lift the crease of the neck diagonally into the center of the head. Make sure your ears are equidistant from your shoulders.

=== Step 3

Reach your arms toward the ceiling, perpendicular to the floor. Rock slightly from side to side and broaden the back ribs and the shoulder blades away from the spine. Then release the arms to the floor, angled evenly relative to the mid-line of torso. Turn the arms outward and stretch them away from the space between the shoulder blades. Rest the backs of the hands on the floor as close as you comfortably can to the index finger knuckles. Make sure the shoulder blades are resting evenly on the floor. Imagine the lower tips of the shoulder blades are lifting diagonally into your back toward the top of the sternum. From here, spread the collarbones.

=== Step 4

In addition to quieting the physical body in Savasana, it's also necessary to pacify the sense organs. Soften the root of the tongue, the wings of the nose, the channels of the inner ears, and the skin of the forehead, especially around the bridge of the nose between the eyebrows. Let the eyes sink to the back of the head, then turn them downward to gaze at the heart. Release your brain to the back of the head.

=== Step 5

Stay in this pose for 5 minutes for every 30 minutes of practice. To exit, first roll gently with an exhalation onto one side, preferably the right. Take 2 or 3 breaths. With another exhalation press your hands against the floor and lift your torso, dragging your head slowly after. The head should always come up last.

=== Finding Stillness in Corpse Pose

Aadil Palkhivala's reply: https://www.yogajournal.com/teach/finding-stillness-in-corpse-pose

Agitation in Savasana is not uncommon--even after a full asana practice, many people still experience difficulty coming to complete stillness and rest.

Since you refer to both agitation and hunger, there are two possibilities:

* Either you have not worked deeply enough during practice to feel a release from day-to-day stress,
*  or you have worked too hard and not had enough nourishment, so your body is aching to come out of the pose and be fed.

First, try a deeper and more vigorous approach to your yoga. This does not mean that you should feel aggressive or violent in your practice, but try working hard enough--whether by focusing your intention, deepening the breath, or holding poses longer--to release tension in your body and give space for the nerves to relax.

I also recommend a small meal two hours before you practice or some fruit one hour before the practice, so that your body does not feel deprived. If you are practicing too vigorously, your breath can serve as a gauge. Watch your breath--if it becomes too rapid, shallow, or tense, please slow down and rest.


Whatever the exact cause of your situation may be, it will help tremendously if you bring your attention to your breath during Savasana. Breathe only through your nose, and start with a slow, deep three- to five-count inhalation. Then, while exhaling, double it to six to 10 counts. Do not force the exhalation--adjust the length of the inhalation so that this is easily possible. Focusing on the breath like this brings the mind to stillness and relaxes excess tension in the nervous system, which aids relaxation.


Recognized as one of the world's top yoga teachers, Aadil Palkhivala began studying yoga at the age of seven with B.K.S. Iyengar was introduced to Sri Aurobindo's yoga three years later. He received the Advanced Yoga Teacher's Certificate at the age of 22 and is the founder-director of internationally-renowned Yoga Centers™ in Bellevue, Washington. Aadil is also a federally-certified Naturopath, a certified Ayurvedic Health Science Practitioner, a clinical hypnotherapist, a certified Shiatsu and Swedish bodywork therapist, a lawyer, and an internationally-sponsored public speaker on the mind-body-energy connection.
