== Shirshasana (or Sirsasana)

* BKS Iyengar - sirsasana yoga pose (correct headstand) https://www.youtube.com/watch?v=2F9uptI0LE0
* https://www.yogajournal.com/poses/6-steps-for-teaching-headstand
* https://www.yogapedia.com/definition/6961/sirsasana

Sanskrit sirsa, meaning “head”

Sirsasana is an advanced inversion that exhibits strength, control and the beauty of overcoming the fear of falling through physical and mental balance.

This full inversion returns blood to the heart and the brain, refreshing the cardiovascular and lymphatic system and providing energizing effects for the whole body.


Spiritual yoga practice

* use this asana to redirect sexual energies into a higher spiritual energy, which is thought to increase wellness and promote a positive aura.
* This higher energy is called ojas, and is thought to assist in heightening other spiritual yogic practices.
* Inversions like sirsasana help in opening the ajna, or third eye, chakra.


=== Preparation

See the ecta sequence
