== Uttanasana - Standing Forward Bend

How to Use Your Shoulders to Deepen Uttanasana:
https://www.dailybandha.com/2011/01/use-your-shoulders-to-deepen-uttanasana.html

*  engage the quadriceps to straighten the knees. A cue for activating the quads is to lift the kneecaps towards the pelvis.

How Tight Hamstrings Affect Your Lumbar Spine:
https://www.dailybandha.com/2011/01/tight-hamstrings-can-affect-your-lumbar.html

* The forward bend should come from the hip joint, rather than the lumbar spine

WARNING: Adjacent joints move in what is known as a “coupled” fashion. When the pelvis tilts back, the lumbar vertebrae flex forward. This means that if the hamstrings are tight and we bend forward in Uttanasana, more of the flexion comes from the lumbar spine. Conversely, when the hamstrings are flexible, the pelvis can tilt forward, allowing the forward bend to come from the hip joint, rather than the lumbar spine.


Ideally, we want to have have a forward bend come predominantly from pelvic movement (pelvic dominance) rather than from the lumbar (lumbar dominance).